on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache collections
        uses: actions/cache@v4
        with:
          path: collections
          key: collections-${{ hashFiles('requirements.yml') }}

      - name: Install collections
        run: |
          ansible-galaxy collection install -r requirements.yml --collections-path collections