on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache collections
        uses: actions/cache@v4
        with:
          path: collections
          key: collections-${{ steps.collections_install.outputs.hash }}

      - name: Install collections if needed
        id: collections_install
        run: |
          COLLECTIONS_DIR="$PWD/collections"
          HASH_FILE="$COLLECTIONS_DIR/ansible_collections.hash"

          # Compute current hash excluding the hash file itself
          CURRENT_HASH=$(find "$COLLECTIONS_DIR" -type f ! -name "$(basename "$HASH_FILE")" | sort | xargs sha256sum | sha256sum | cut -f1 -d' ')

          if [ ! -f "$HASH_FILE" ] || [ "$CURRENT_HASH" != "$(cat "$HASH_FILE")" ]; then
            echo "Installing collections (hash mismatch or missing)..."
            ansible-galaxy collection install -r "$PWD/requirements.yml" --collections-path "$COLLECTIONS_DIR" --force

            # Recompute hash *after* install
            UPDATED_HASH=$(find "$COLLECTIONS_DIR" -type f ! -name "$(basename "$HASH_FILE")" | sort | xargs sha256sum | sha256sum | cut -f1 -d' ')
            echo "$UPDATED_HASH" > "$HASH_FILE"
          else
            echo "Collections are up to date. Skipping installation."
          fi
          echo "hash=$CURRENT_HASH" >> $GITHUB_OUTPUT