name: Ansible Collections → OCI

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache externals
        uses: actions/cache@v4
        with:
          path: external
          key: external-${{ hashFiles('./external/requirements.yml', './external/requirements.txt') }}

      - name: Set up Python virtualenv
        run: |
          PYTHON_VENV="./external/python/venv"
          python3 -m venv "$PYTHON_VENV"
          source "$PYTHON_VENV/bin/activate"
          pip install --upgrade pip
          pip install -r "./external/requirements.txt"

      - name: Install roles
        run: |
          if [ -f ./external/requirements.yml ]; then
            mkdir -p ./external
            ansible-galaxy role install -r ./external/requirements.yml -p ./external/roles
          else
            echo "Ansible requirements.yml not found. Skipping roles download."
          fi

      - name: Install collections
        run: |
          if [ -f ./external/requirements.yml ]; then
            mkdir -p ./external
            ansible-galaxy collection install -r ./external/requirements.yml --collections-path ./external/collections
          else
            echo "Ansible requirements.yml not found. Skipping collections download."
          fi

      - name: Write OCI config and key
        run: |
          mkdir -p ~/.oci
          cat <<EOF > ~/.oci/config
          ${{ secrets.OCI_CONFIG }}
          EOF
          echo "${{ secrets.OCI_API_KEY_BASE64 }}" | base64 -d > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem
          cat ~/.oci/config
          ls -l ~/.oci/oci_api_key.pem

      - name: Run playbook (example)
        run: |
          source "./external/python/venv/bin/activate"
          export ANSIBLE_COLLECTIONS_PATH=./external/collections
          ansible-playbook greetings.yml

      - name: Run playbook (OCI example)
        run: |
          source "./external/python/venv/bin/activate"
          export ANSIBLE_COLLECTIONS_PATH=./external/collections
          ansible-playbook get_namespace.yml