on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache externals
        uses: actions/cache@v4
        with:
          path: external
          key: external-${{ hashFiles('./external/requirements.yml') }}

      - name: Install roles
        run: |
          if [ -f ./external/requirements.yml ]; then
            mkdir -p ./external
            ansible-galaxy role install -r ./external/requirements.yml -p ./external/roles
          else
            echo "Ansible requirements.yml not found. Skipping roles download."
          fi

      - name: Install collections
        run: |
          if [ -f ./external/requirements.yml ]; then
            mkdir -p ./external
            ansible-galaxy collection install -r ./external/requirements.yml --collections-path ./external/collections
          else
            echo "Ansible requirements.yml not found. Skipping collections download."
          fi