on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache collections
        uses: actions/cache@v4
        with:
          path: collections
          key: collections-${{ steps.collections_install.outputs.collections_hash }}

      - name: Install collections if needed
        id: collections_install
        run: |
          source .github/workflows/bin/install_collections.sh 
          echo "collections_hash=$CURRENT_HASH" >> $GITHUB_OUTPUT