on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache collections
        uses: actions/cache@v4
        with:
          path: collections
          key: collections-${{ hashFiles('requirements.yml') }}

      - name: Cache roles
        uses: actions/cache@v4
        with:
          path: roles
          key: roles-${{ hashFiles('requirements.yml') }}

      - name: Install roles
        run: |
          if [ -f requirements.yml ]; then
            ansible-galaxy role install -r requirements.yml -p ./roles
          else
            Ansible requirements.yml not found. Skipping roles download.
          fi

      - name: Install collections
        run: |
          if [ -f requirements.yml ]; then
            ansible-galaxy collection install -r requirements.yml --collections-path ./collections
            ansible-galaxy role install -r requirements.yml -p ./roles
          else
            Ansible requirements.yml not found. Skipping collections download. 
          fi